# GRADLE_PORTAL_KEY (base64)
# GRADLE_PORTAL_SECRET (base64)
# GITHUB_TOKEN
# NEXUS_USER (base64)
# NEXUS_PASS (base64)
# GPG_PASSPHRASE (base64)
# GPG_KEY (base64)
#   gpg --export-secret-keys --armor KEY_ID | openssl base64 | pbcopy

name: deploy
on:
  workflow_dispatch:
    inputs:
      to_publish:
        description: 'What to publish'
        required: true
        default: 'all'
        type: choice
        options:
          - plugin-gradle
          - plugin-maven
          - solstice
          - all
jobs:
  build:
    runs-on: ubuntu-latest
    name: deploy
    env:
      gh_token: ${{ secrets.EQUO_IDE_GITHUB }}
      ORG_GRADLE_PROJECT_nexus_user: ${{ secrets.NEXUS_USER }}
      ORG_GRADLE_PROJECT_nexus_pass: ${{ secrets.NEXUS_PASS }}
      ORG_GRADLE_PROJECT_gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
      ORG_GRADLE_PROJECT_gpg_key64: ${{ secrets.GPG_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: jdk 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: gradle caching
        uses: gradle/gradle-build-action@v2
      - name: publish all
        if: "${{ github.event.inputs.to_publish == 'all' }}"
        run: |
          ./gradlew :solstice:changelogPush -Prelease=true --stacktrace --warning-mode all
          ./gradlew :plugin-maven:changelogPush -Prelease=true --stacktrace --warning-mode all
          ./gradlew :plugin-gradle:changelogPush -Prelease=true -Pgradle.publish.key=${{ secrets.GRADLE_PORTAL_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PORTAL_SECRET }} --stacktrace --warning-mode all
      - name: publish just plugin-gradle
        if: "${{ github.event.inputs.to_publish == 'plugin-gradle' }}"
        run: |
          ./gradlew :plugin-gradle:changelogPush -Prelease=true -Pgradle.publish.key=${{ secrets.GRADLE_PORTAL_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PORTAL_SECRET }} --stacktrace --warning-mode all
      - name: publish just plugin-maven
        if: "${{ github.event.inputs.to_publish == 'plugin-maven' }}"
        run: |
          ./gradlew :plugin-maven:changelogPush -Prelease=true --stacktrace --warning-mode all
      - name: publish just solstice
        if: "${{ github.event.inputs.to_publish == 'solstice' }}"
        run: |
          ./gradlew :solstice:changelogPush -Prelease=true --stacktrace --warning-mode all
